package server

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/VexoaXYZ/inkwash/pkg/types"
)

const serverConfigTemplate = `#     _       _                        _
#    (_)     | |                      | |
#     _  _ __| | ____      ____ _ ___| |__
#    | || '_ \ |/ /\ \ /\ / / _' / __| '_ \
#    | || | | |   <  \ V  V / (_| \__ \ | | |
#    |_||_| |_|_|\_\  \_/\_/ \__,_|___/_| |_|
#
# Server Configuration - Generated by Inkwash
# Learn more: https://docs.fivem.net/docs/server-manual/server-commands/

## ═══════════════════════════════════════════════════════════════
##  Server Identity
## ═══════════════════════════════════════════════════════════════

sv_hostname "{{.ServerName}}"
sv_licenseKey "{{.LicenseKey}}"
sv_maxclients {{.MaxPlayers}}

## Server Endpoints
endpoint_add_tcp "0.0.0.0:{{.Port}}"
endpoint_add_udp "0.0.0.0:{{.Port}}"

## ═══════════════════════════════════════════════════════════════
##  Core Resources
## ═══════════════════════════════════════════════════════════════

ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap

## ═══════════════════════════════════════════════════════════════
##  Server Information (Server Browser)
## ═══════════════════════════════════════════════════════════════

sets sv_projectName "{{.ServerName}}"
sets sv_projectDesc "FiveM Server powered by Inkwash CLI"
sets locale "en-US"
sets tags "inkwash, default"

## Game Type (Freeroam, Roleplay, etc)
sets gametype "Freeroam"

## ═══════════════════════════════════════════════════════════════
##  Permissions & Security
## ═══════════════════════════════════════════════════════════════

add_ace group.admin command allow
add_ace group.admin command.quit deny
add_principal identifier.steam:YOUR_STEAM_ID group.admin

## ═══════════════════════════════════════════════════════════════
##  Logging & Monitoring
## ═══════════════════════════════════════════════════════════════

set sv_logFile "logs/server.log"
set sv_endpointprivacy true

## Rcon Configuration (Optional - Uncomment to enable)
# rcon_port {{.Port}}
# rcon_password "YOUR_SECURE_PASSWORD_HERE"

## ═══════════════════════════════════════════════════════════════
##  Steam Web API (Optional - Improves Steam integration)
## ═══════════════════════════════════════════════════════════════
## Get your key from: https://steamcommunity.com/dev/apikey
# set steam_webApiKey "YOUR_STEAM_API_KEY"

## ═══════════════════════════════════════════════════════════════
##  OneSync (Recommended for player capacity > 32)
## ═══════════════════════════════════════════════════════════════
# set onesync on

## ═══════════════════════════════════════════════════════════════
##  Server Configuration
## ═══════════════════════════════════════════════════════════════

set sv_enforceGameBuild 2802
sv_scriptHookAllowed 0

## ═══════════════════════════════════════════════════════════════
##  Add your custom resources below this line
## ═══════════════════════════════════════════════════════════════

# ensure your-resource-name
`

// ConfigGenerator generates server configuration files
type ConfigGenerator struct{}

// NewConfigGenerator creates a new config generator
func NewConfigGenerator() *ConfigGenerator {
	return &ConfigGenerator{}
}

// GenerateServerConfig generates a server.cfg file
func (cg *ConfigGenerator) GenerateServerConfig(server *types.Server, licenseKey string) error {
	tmpl, err := template.New("server.cfg").Parse(serverConfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	configPath := filepath.Join(server.Path, "server.cfg")
	file, err := os.Create(configPath)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	data := struct {
		ServerName  string
		LicenseKey  string
		MaxPlayers  int
		Port        int
	}{
		ServerName: server.Name,
		LicenseKey: licenseKey,
		MaxPlayers: 32,
		Port:       server.Port,
	}

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to generate config: %w", err)
	}

	return nil
}

// GenerateLaunchScript generates platform-specific launch script
func (cg *ConfigGenerator) GenerateLaunchScript(server *types.Server) error {
	scriptPath, scriptContent := cg.getScriptTemplate(server)

	if err := os.WriteFile(scriptPath, []byte(scriptContent), 0755); err != nil {
		return fmt.Errorf("failed to create launch script: %w", err)
	}

	return nil
}

// getScriptTemplate returns the script path and content for the platform
func (cg *ConfigGenerator) getScriptTemplate(server *types.Server) (string, string) {
	if isWindows() {
		scriptPath := filepath.Join(server.Path, "run.cmd")
		content := fmt.Sprintf(`@echo off
cd /d "%s"
bin\FXServer.exe +exec server.cfg
`, server.Path)
		return scriptPath, content
	}

	// Linux
	scriptPath := filepath.Join(server.Path, "run.sh")
	content := fmt.Sprintf(`#!/bin/bash
cd "%s"
bash bin/run.sh +exec server.cfg
`, server.Path)
	return scriptPath, content
}

func isWindows() bool {
	return os.PathSeparator == '\\'
}
